language: python
python:
  - "2.7"

install:
    - pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/develop.zip
    - pip install .
    - pip install flake8

script:
    - flake8 .
    - nosetests cloudify_openstack/tests
