language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - sudo pip install . --process-dependency-links
    - sudo pip install flake8


script:

    - flake8 .
    # command to run tests
    - nosetests cloudify_openstack/tests