language: python
python:
  - "2.7"

install:
    - git clone https://github.com/cloudify-cosmo/cloudify-cli --depth=1
    - cd cloudify-cli; pip install . -r requirements.txt; cd ..
    - pip install . -r requirements.txt
    - pip install flake8

script:
    - flake8 . --exclude docs
    - nosetests cloudify_openstack/tests
notifications:
    flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f